# reference: https://github.com/rust-lang/cargo/issues/3946
[env]
RUSTFLAGS     = "--cfg tokio_unstable"
WORKSPACE_DIR = { value = "", relative = true }

[build]
rustflags = ["--cfg", "tokio_unstable"]

[alias]
ls-lint     = "run --bin ls-lint"
run-fixture = "run --bin run-fixture"

[target.'cfg(target_vendor = "apple")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains", "--cfg", "tokio_unstable"]

# To be able to run unit tests on Linux, support compilation to 'x86_64-unknown-linux-gnu'.
[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-args=-Wl,--warn-unresolved-symbols", "--cfg", "tokio_unstable"]

# To be able to run unit tests on Windows, support compilation to 'x86_64-pc-windows-msvc'.
[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "link-args=/FORCE", "--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg", "tokio_unstable"]
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "--cfg", "tokio_unstable"]
